# 商用程式設計
## 2021/04/30
# Chap 4 Numpy套件
## 為什麼需要numpy?
* numpy由c撰寫，速度快python 10~1000倍以上
* numpy儲存結果較正確，python數字儲存不正確
* numpy節省記憶體儲存空間
* numpy的向量(矩陣計算)速度快
* numpy的取值方便

## Numpy的乘法

In [1]:
import numpy as np
source = [1,2,3,4,5]
array=np.array(source)#轉換成numpy陣列
print(source*4)
print(array*4)#會對每筆資料做乘法，而不是乘以幾次的資料

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 4  8 12 16 20]


## ndarray.shape 陣列維度的形狀
## ndarray.dtype 陣列的資料型態
## ndarray.ndim 陣列的維度

In [2]:
import numpy as np
array=np.array([1,2,3,4,5])
print(type(array))#取得變數型態
print(array.shape)
print(array.dtype)
print(array.ndim)

<class 'numpy.ndarray'>
(5,)
int32
1


## numpy.zeros 產生資料為0的陣列
## numpy.empty 產生資料為空的陣列
## numpy.arange 產生指定範圍、間距的等差陣列

In [3]:
import numpy as np
a = np.zeros(6)#產生6筆資料為零的陣列
b = np.empty((2,3,4))#產生資料為空的2*3*4之3維陣列
c = np.arange(10)#產生0~10的陣列，另可設定起始值及間隔值

print(a)
print(b)
print(c)

[0. 0. 0. 0. 0. 0.]
[[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.29061074e-306]
  [1.69119873e-306 1.78019082e-306 1.89146896e-307 7.56571288e-307]
  [3.11525958e-307 1.24610723e-306 1.37962320e-306 1.29060871e-306]]

 [[2.22518251e-306 1.33511969e-306 1.78022342e-306 1.05700345e-307]
  [1.11261027e-306 1.11261502e-306 1.42410839e-306 7.56597770e-307]
  [6.23059726e-307 1.42419530e-306 7.56599128e-307 7.23168527e-308]]]
[0 1 2 3 4 5 6 7 8 9]


## 2維陣列取值

In [4]:
import numpy as np
a = np.array((np.arange(0,3),np.arange(7,10)))

print(a)
print(a[0,:])#取所有在1維中index為0的資料
print(a[:,0])#取所有在2維中index為0的資料
print(a[1,1])#取1維index為1且2維index為1的資料

[[0 1 2]
 [7 8 9]]
[0 1 2]
[0 7]
8


## ndarray.reshape 重新定義陣列維度形狀(須符合舊有資料的數量)

In [5]:
import numpy as np
a = np.arange(10)
print(a)
print(a.shape)
a = a.reshape(2,5)
print(a)#資料會隨著陣列大小重新編排
print(np.arange(100).reshape(10,10))

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


## numpy.nan 空值

In [6]:
import numpy as np
a = np.array([10,54,17,56,np.nan])
print(a)

[10. 54. 17. 56. nan]
